version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(levelname)-10s %(asctime)s  - %(name)s %(message)s"

    debug:
        format: "%(levelname)-10s %(asctime)s  - %(name)-20s %(pathname)-60s #%(lineno)-5s %(funcName)-20s %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: ERROR
        formatter: simple
        stream: ext://sys.stdout

    error_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: D
        level: ERROR
        formatter: debug
        filename: logs/errors.log
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: D
        level: DEBUG
        formatter: debug
        filename: logs/debug.log
        encoding: utf8

loggers:
    application.server:
        level: INFO
        handlers: [console, debug_file_handler, error_file_handler]
        propagate: yes
    werkzeug:
        level: INFO
        handlers: [console, debug_file_handler, error_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, debug_file_handler, error_file_handler]
    handlers: [console, debug_file_handler, error_file_handler]
