version: 1

disable_existing_loggers: False

formatters:
    simple:
        format: "%(process)d %(levelname)-10s %(asctime)s  - %(name)-20s %(message)s"

    debug:
        format: "%(process)d %(levelname)-10s %(asctime)s  - %(name)-20s %(pathname)-60s #%(lineno)-5s %(funcName)-20s %(message)s"

    # The 'exc_info' part is relevant with the logging.exception() call.
    error:
        format: "%(process)d %(levelname)-10s %(asctime)s  - %(name)-20s %(pathname)-60s #%(lineno)-5s %(funcName)-20s %(message)s\n%(exc_info)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    error_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: D
        level: ERROR
        formatter: error
        filename: logs/errors.log
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: D
        level: DEBUG
        formatter: debug
        filename: logs/debug.log
        encoding: utf8

loggers:
    application.server:
        level: INFO
        handlers: [console, debug_file_handler, error_file_handler]
        propagate: yes
    werkzeug:
        level: INFO
        handlers: [console, debug_file_handler, error_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, debug_file_handler, error_file_handler]
