version: 1

disable_existing_loggers: False

formatters:
    audit:
        format: "%(asctime)s  - %(name)s %(pathname)-12.12s#%(lineno)-5.5s %(funcName)-20.20s %(message)s"

handlers:
    logpath: logs

    console:
        class: logging.StreamHandler
        level: INFO
        formatter: audit
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: D
        level: INFO
        formatter: audit
        filename: logs/info.log
        encoding: utf8

    error_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: D
        level: ERROR
        formatter: audit
        filename: logs/errors.log
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        when: D
        level: DEBUG
        formatter: audit
        filename: logs/debug.log
        encoding: utf8

loggers:
    application.server:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: yes
    werkzeug:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
